export enum DegreeEnum {
  BACHELOR_OF_SCIENCE = "BACHELOR_OF_SCIENCE",
  BACHELOR_OF_ARTS = "BACHELOR_OF_ARTS",
  MASTERS = "MASTERS",
  PHD = "PHD",
  UNDERGRADUATE = "UNDERGRADUATE",
}

export enum EmploymentTypeEnum {
  CONTRACT = "CONTRACT",
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME",
  FREELANCING = "FREELANCING",
}
